// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RunScript(arg1:string):Promise<void>;

export function RunScriptIncrement(arg1:string):Promise<void>;
