// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RunScript(arg1) {
  return window['go']['main']['App']['RunScript'](arg1);
}

export function RunScriptIncrement(arg1) {
  return window['go']['main']['App']['RunScriptIncrement'](arg1);
}
